nome = input('Digite seu nome completo: ')
print('Analisando seu nome...')
print('Seu nome em maiúsculo é:', nome.upper())
print('Seu nome em minúsculo é:', nome.lower())
print('Seu nome ao todo tem o total de {} letras', format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras', format(nome.find(' ')))